import { expect, test } from '@playwright/test';
import { examples } from '../../src/examples';

test('编译、单步、运行、验证与模型切换', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'CPU 实时状态' })).toBeVisible();
  await page.getByRole('button', { name: '单步', exact: true }).click();
  await expect(page.locator('.register').first()).toContainText('000000000000000A');
  await page.getByRole('button', { name: '重置执行', exact: true }).click();
  await page.getByLabel('执行速度').selectOption('120');
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await expect(page.locator('.status-badge')).toHaveText('已完成', { timeout: 15000 });
  await expect(page.locator('.output-line')).toContainText('55');
  await page.getByRole('button', { name: '结果验证', exact: true }).click();
  await expect(page.locator('.validation-summary')).toContainText('验证通过');
  await page.getByLabel('CPU 架构').selectOption('arm64');
  await expect(page.locator('.register').first()).toContainText('X0');
  await expect(page.locator('.cpu-metrics').first()).toContainText('0steps');
  await page.getByLabel('C++ 源代码编辑器').fill('int main() { int answer = 6 * 7; std::cout << answer; return 0; }');
  await page.getByRole('button', { name: '编译', exact: true }).click();
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await expect(page.locator('.status-badge')).toHaveText('已完成');
  await page.getByRole('button', { name: '控制台', exact: false }).click();
  await expect(page.locator('.output-line')).toContainText('42');
  expect(errors).toEqual([]);
});

test('编译错误恢复、示例选择、内存与移动端布局', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByLabel('C++ 源代码编辑器').fill('int main() { return missing; }');
  await page.getByRole('button', { name: '编译', exact: true }).click();
  await expect(page.locator('.console-line.error-text')).toContainText('未声明');
  page.on('dialog', dialog => dialog.accept());
  await page.getByLabel('示例程序').selectOption('bits');
  await page.getByLabel('执行速度').selectOption('120');
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await expect(page.locator('.status-badge')).toHaveText('已完成');
  await page.getByRole('button', { name: '内存', exact: true }).click();
  await expect(page.locator('.byte-table')).toContainText('0C');
  await page.getByRole('button', { name: '结果验证', exact: true }).click();
  await expect(page.locator('.validation-summary')).toContainText('验证通过');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: '指南', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toBeHidden();
});

test('用户 class 示例编译运行、单步成员高亮和内存布局', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('C++ 源代码编辑器').fill(examples.find(example => example.id === 'class-members')!.source);
  await page.getByRole('button', { name: '编译', exact: true }).click();
  await expect(page.locator('.status-badge')).toHaveText('就绪');
  const x = page.locator('.memory-content tr').filter({ has: page.getByRole('cell', { name: 'a.x', exact: true }) });
  const y = page.locator('.memory-content tr').filter({ has: page.getByRole('cell', { name: 'a.y', exact: true }) });
  for (let i = 0; i < 6; i++) await page.getByRole('button', { name: '单步', exact: true }).click();
  await expect(x.locator('.variable-value')).toHaveText('1');
  await expect(x).toHaveClass('memory-changed');
  await expect(y.locator('.variable-value')).toHaveText('0');
  await page.getByLabel('执行速度').selectOption('120');
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await expect(page.locator('.status-badge')).toHaveText('已完成');
  await expect(y.locator('.variable-value')).toHaveText('2');
  await expect(page.locator('.console-content')).toContainText('返回值 0');
  await page.getByRole('button', { name: '内存', exact: true }).click();
  const bytes = page.locator('.byte-table tbody tr');
  await expect(bytes.nth(0)).toContainText('0x1000');
  await expect(bytes.nth(0).locator('.byte')).toHaveText(['01', '00', '00', '00']);
  await expect(bytes.nth(1)).toContainText('0x1004');
  await expect(bytes.nth(1).locator('.byte')).toHaveText(['02', '00', '00', '00']);
  page.on('dialog', dialog => dialog.accept());
  await page.getByLabel('示例程序').selectOption('class-members');
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await expect(page.locator('.status-badge')).toHaveText('已完成');
  await page.getByRole('button', { name: '结果验证', exact: true }).click();
  await expect(page.locator('.validation-summary')).toContainText('4 / 4 项预期结果一致');
});

test('CPU 示意图按指令更新 PC、IR、ALU、实际地址并响应重置和架构切换', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('C++ 源代码编辑器').fill('int main() { int a = 3; a += 4; if (a == 0) { a = 9; } return a; }');
  await page.getByRole('button', { name: '编译', exact: true }).click();
  await expect(page.getByTestId('diagram-pc')).toContainText('0x00400000');
  await expect(page.getByTestId('diagram-ir')).toContainText('等待取指');
  const single = page.getByRole('button', { name: '单步', exact: true });
  await single.click();
  await expect(page.getByTestId('diagram-ir')).toContainText('MOV RAX, 3');
  await expect(page.getByTestId('diagram-pc')).toContainText('0x00400004');
  await single.click();
  await expect(page.getByTestId('diagram-access')).toContainText('WRITE');
  await expect(page.getByTestId('diagram-access')).toContainText('0x00001000');
  await expect(page.getByTestId('diagram-access')).toContainText('a = 3');
  await single.click();
  await expect(page.getByTestId('diagram-access')).toContainText('READ');
  await single.click();
  await single.click();
  await expect(page.getByTestId('diagram-alu')).toContainText('结果 = 7');
  await expect(page.getByTestId('diagram-alu').locator('.alu-operand')).toHaveText('A3B4');
  for (let i = 0; i < 5; i++) await single.click();
  await expect(page.getByTestId('diagram-branch')).toContainText('已跳转');
  await expect(page.getByTestId('diagram-pc')).toContainText('0x00400030');
  await page.getByRole('button', { name: '展开 CPU 示意图', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'CPU 动态示意图' })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByLabel('执行速度').selectOption('120');
  await page.getByRole('button', { name: '运行', exact: true }).click();
  await expect(page.locator('.status-badge')).toHaveText('已完成');
  await expect(page.getByTestId('diagram-ir')).toContainText('RET');
  await expect(page.locator('.diagram-io')).toContainText('return 7');
  await page.getByLabel('CPU 架构').selectOption('arm64');
  await expect(page.getByTestId('diagram-ir')).toContainText('等待取指');
  await expect(page.getByTestId('diagram-access')).toContainText('总线空闲');
  await single.click();
  await expect(page.getByTestId('diagram-ir')).toContainText('MOV X0, #3');
  await page.getByRole('button', { name: '重置执行', exact: true }).click();
  await expect(page.getByTestId('diagram-pc')).toContainText('0x00400000');
  await expect(page.getByTestId('diagram-alu')).toContainText('等待运算');
});
